version: '3.9'

networks:
  local:
    name: local

services:
  cityinfoapi:
    container_name: cityinfoapi
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - Mode=Debug
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Password1!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_HTTPS_PORT=8001
    ports:
      - "8000:80"
      - "8001:443"
    depends_on:
      - cityinfodb
      - cityinfocache
    networks:
      - local
    volumes:
      - ~/.aspnet/https:/https:ro
  
  cityinfodb:
    image: postgres:latest
    container_name: cityinfodb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=4T66Rk9A#JE4y7V%
      - POSTGRES_DB=CityInfo
    restart: always
    ports:
      - "5432:5432"
    networks:
      - local
    volumes:
      - .postgres/:/var/lib/postgresql/data/
  
  cityinfocache:
    image: bitnami/redis:latest
    container_name: cityinfocache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 22!ueVnUG*@7mu@M
    networks:
      - local
    working_dir: /data
    volumes:
      - .redis/:/data